version: "3"
name: portfolio-infra
services:
  database:
    image: "postgres:15"
    container_name: portfolio-infra-db
    env_file:
      - ./config/database.env
    ports:
      - "5432:5432"
    volumes:
      - ./_database:/var/lib/postgresql/data
