spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    # TODO the following password is wrong, which application.yaml file is actually used ??
    password: 12345
    url: jdbc:postgresql://localhost:5432/portfoliodb
    username: postgres

logging:
  level:
    root: info
    org.hibernate: info
    org.springframework.jdbc: info
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql:
#              basicBinder: trace
#      springframework:
#        jdbc:
#          core:
#            jdbcTemplate: debug
#            statementCreatorUtils: trace
